// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVd9RobBy3IVdTrT21aTQDTApYOfjaelY',
    appId: '1:1085869227798:web:13fd0621b515a827e31a37',
    messagingSenderId: '1085869227798',
    projectId: 'safety-jacket-71ad8',
    authDomain: 'safety-jacket-71ad8.firebaseapp.com',
    databaseURL: 'https://safety-jacket-71ad8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-jacket-71ad8.firebasestorage.app',
    measurementId: 'G-8TGWTLTEZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhFXk14y2VXlyrmjsXO4TcAbHTVz0kge0',
    appId: '1:1085869227798:android:cfbd272975c389a3e31a37',
    messagingSenderId: '1085869227798',
    projectId: 'safety-jacket-71ad8',
    databaseURL: 'https://safety-jacket-71ad8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-jacket-71ad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKfEWiHyiWBDzQsHMYp5O_pKlZ3kfuAxM',
    appId: '1:1085869227798:ios:67bd3f08b53f6219e31a37',
    messagingSenderId: '1085869227798',
    projectId: 'safety-jacket-71ad8',
    databaseURL: 'https://safety-jacket-71ad8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-jacket-71ad8.firebasestorage.app',
    iosBundleId: 'com.example.safetyjacketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKfEWiHyiWBDzQsHMYp5O_pKlZ3kfuAxM',
    appId: '1:1085869227798:ios:67bd3f08b53f6219e31a37',
    messagingSenderId: '1085869227798',
    projectId: 'safety-jacket-71ad8',
    databaseURL: 'https://safety-jacket-71ad8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-jacket-71ad8.firebasestorage.app',
    iosBundleId: 'com.example.safetyjacketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVd9RobBy3IVdTrT21aTQDTApYOfjaelY',
    appId: '1:1085869227798:web:5d1b0b82c6a767abe31a37',
    messagingSenderId: '1085869227798',
    projectId: 'safety-jacket-71ad8',
    authDomain: 'safety-jacket-71ad8.firebaseapp.com',
    databaseURL: 'https://safety-jacket-71ad8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-jacket-71ad8.firebasestorage.app',
    measurementId: 'G-TCWEF24ZEM',
  );

}